---
settings:
  name: Announcements
  rss_page: index.html
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    lipi_enabled: false
    harmony_enabled: false
    langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,fr-fr
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,fr-fr
sidebar:
  entries:
  - title: Willkommen!
    url: "/index.html"
  - title: '2021'
    entries:
    - title: Dokumente für die Astra Produktfamilie
      url: "/astra-family.html"
    - title: Dokumentation für Astra Data Store
      url: "/astra-data-store.html"
    - title: Dokumentation für Astra Trident
      url: "/astra-trident.html"
    - title: Docs für Astra Control Center
      url: "/astra_control_center.html"
    - title: Standardzweig in Haupt umbenannt
      url: "/default-branch-rename.html"
  - title: '2020'
    entries:
    - title: Aktualisierung des NetApp HCI-Doc
      url: "/hci-update.html"
    - title: Laden Sie eine PDF herunter
      url: "/pdfs.html"
    - title: Verbesserter Benutzerfreundlichkeit
      url: "/look-and-feel.html"
    - title: Docs für ONTAP System Manager
      url: "/ontap-system-manager.html"
    - title: Dokumentation für Cloud Compliance
      url: "/cloud-compliance.html"
    - title: Dokumente für ONTAP Select
      url: "/ontap-select.html"
  - title: '2019'
    entries:
    - title: Dokumentation für NetApp HCI Cloud-Services und -Lösungen
      url: "/hci.html"
    - title: Stilleitfaden und Syntaxreferenz
      url: "/style-and-syntax.html"
    - title: Docs für SaaS Backup für Salesforce
      url: "/salesforce.html"
    - title: Dokumente für Active IQ
      url: "/active-iq.html"
    - title: RSS-Feeds zu neuen Seiten
      url: "/rss.html"
    - title: Dokumente für Cloud Tiering
      url: "/cloud-tiering.html"
    - title: GitHub Avatare für Autoren
      url: "/avatars.html"
  - title: '2018'
    entries:
    - title: Syntax-Hervorhebung
      url: "/syntax.html"
    - title: Navigation auf Seitenebene
      url: "/navigation.html"
    - title: Dokumentation für Converged Systems Advisor
      url: "/converged-systems-advisor.html"
    - title: Neue Methode zum anfordern von Dokumentänderungen
      url: "/request-doc-changes.html"
    - title: Dokumente für Cloud Insights
      url: "/cloud-insights.html"
    - title: Dokumente für Cloud Volumes ONTAP
      url: "/cloud-volumes-ontap.html"
    - title: Dokumente für Cloud Volumes Service für AWS
      url: "/cloud-volumes-service.html"
    - title: Docs für SaaS Backup für Office 365
      url: "/office365.html"
    - title: 'Wir stellen vor: NetApp Dokumentation in GitHub'
      url: "/introduction.html"
